// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS_CORE_QccPttKeyDownCheck.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS_CORE_QccPttVirtualKeyCodeToChar.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS_CORE_ResourcesUpdater.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckEditedAliases.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckExistingAliases.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckFalconUpdates.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_DeleteAliasCommands.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_DeleteAliasKeys.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_GetAliasesFilePath.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_GetMenuData.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_RadioCommandsGenerator.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_SaveAliasCommands.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_SaveAliasKeys.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_SplitAliasCommand.VAInline.main")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a lowercase main method.", Scope = "member", Target = "~M:AVCS4_BMS_SplitWildcardAliases.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS_CORE_QccPttKeyDownCheck.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS_CORE_QccPttVirtualKeyCodeToChar.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS_CORE_ResourcesUpdater.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckEditedAliases.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckExistingAliases.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_CheckFalconUpdates.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_DeleteAliasCommands.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_DeleteAliasKeys.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_GetAliasesFilePath.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_GetMenuData.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_RadioCommandsGenerator.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_SaveAliasCommands.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_SaveAliasKeys.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_SplitAliasCommand.VAInline.main")]
[assembly: SuppressMessage("Style", "CA1822:Mark members as static", Justification = "This project is a de facto editor for inlines outside VA, and open source repo, and VA inlines require a non-static main method.", Scope = "member", Target = "~M:AVCS4_BMS_SplitWildcardAliases.VAInline.main")]
